### ISSUE TITLE
crypttab not correctly updated

### ISSUE THREAD

**Issue by Nicocha30** [osresearch/safeboot#32]
Hi!

When running `safeboot luks-seal`, the `crypttab` is not always updated.
Indeed, some `crypttab` entries doesn't contains the `discard` option (it seems only used on disks with trim support).

https://github.com/osresearch/safeboot/blob/e64f69d923101dbb5b1b63ef745cf2075ed6b6b2/sbin/safeboot#L581

Tested with *qemu*, *virtio* disk, Ubuntu 20.04 LTS (Server).

For reference, here is the original `crypttab` after a clean installation:

```
dm_crypt-0 UUID=72b836e1-9bd0-40f7-866d-74836b1e3fab none luks
```

Thanks,

Nicolas

**Comment by osresearch** [comment]
Perhaps this would be a better sed replacement?
```
s: luks: keyscript=/usr/sbin/safeboot-tpm-unseal,luks:
```

**Comment by Nicocha30** [comment]
Yes! I just tested it, it seems to work.
