### ISSUE TITLE
typo in sign-kernel

### ISSUE THREAD

**Issue by Nicocha30** [osresearch/safeboot#33]
Hi!

There is a typography error on the *sign-kernel* function:

https://github.com/osresearch/safeboot/blob/772ae2cef7840305072fd392c6339f3a8d443984/sbin/safeboot#L673

*cmldine* should be written *cmdline*

Thanks,

Nicolas

**Comment by osresearch** [comment]
Whoops. Thanks!

That sort of typo is not caught by `shellcheck`.  It wouldn't affect anyone using the `safeboot linux-sign` or `safeboot recovery-sign` since they pass in kernel command line arguments, but it would be problematic if you called `safeboot sign-kernel` directly.
