### ISSUE TITLE
Possibly wrong environment variable for TPM access

### ISSUE THREAD

**Issue by miczyg1** [osresearch/safeboot#47]
Using tpm2-tools when the system is already launched resulted in "permission denied" and for root "device or resource busy for the user". Using the safeboot luks-seal subcommand complained with same errors. In my case it has been resolved by adding `TPM2TOOL_TCTI=device:/dev/tpmrm0`. `TSS2ENGINE_TCTI` could be invalid?

**Comment by osresearch** [comment]
Yes, that was a mistake.  `TPM2TSSENGINE_TCTI` is for the FAPI version of the tools.
