### ISSUE TITLE
safeboot 0.6 release package does not contain tpm2-attest

### ISSUE THREAD

**Issue by miczyg1** [osresearch/safeboot#49]
Is this intentional? There is no tpm2-attest script in the Debian package https://github.com/osresearch/safeboot/releases/download/release-0.6/safeboot_0.6_amd64.deb

**Comment by osresearch** [comment]
There hasn't been a release since the tpm2 attestation patches were merged in the `tpm2-tools` tree.  I need to re-release.

**Comment by osresearch** [comment]
You can also grab the latest debian package as an artifact built by the CI system from https://github.com/osresearch/safeboot/actions?query=workflow%3A%22Build+Debian+package+on+ubuntu+20.04%22

Unfortunately github doesn't make it possible to link directly to the "latest artifact" for some reason. There are lots of open requests for it, such as https://github.com/actions/upload-artifact/issues/51
