### ISSUE TITLE
tpm2-attest script "tpm2 command not found"

### ISSUE THREAD

**Issue by miczyg1** [osresearch/safeboot#50]
tpm2-attest script contains tpm2 commands similar to those from tpm2-tools however, without underscore. Trying to generate quote results in tpm2 command not found.

I have been using the packaged tpm2-tools and tpm2-abrmd from Ubuntu 20.04. What should be the correct revision of the tools?

**Comment by osresearch** [comment]
`tpm2-tools` merged a patch recently that creates a single busybox style executable for all of the tools.  This is not yet in any of the distro repos, so it is necessary to build `tpm2-tools` (and the tss2 libraries) from source.  The `safeboot.deb` package *should* have the right version of the `tpm2` executable included; I need to update the pinned version for the submodules and re-release.

`tpm2-abrmd` is not required for safeboot; I've found that for most uses the in-kernel one is fine, along with having the scripts manually manage the resources.  This might conflict with IMA if it is in use, although I haven't tested it.
