### ISSUE TITLE
Lack of reference good-pcrs.txt file and format documentation

### ISSUE THREAD

**Issue by miczyg1** [osresearch/safeboot#52]
It would be great and helpful to have a reference of good-pcrs.txt file for eventlog validation and some documentation how it is formatted.

**Comment by osresearch** [comment]
Excellent idea.  Ideally we would have a "first principles" way of generating the PCRs based on reproducible firmware builds and configuration data, although for most platforms it is really only possible to record a set of "golden PCRs" based on a clean boot.

**Comment by osresearch** [comment]
I've added a test for the `tpm2-attest verify` with the PCRs on my t490 (and found a bug, which is the best sort of test!). https://github.com/osresearch/safeboot/commit/db1905ba3c2e45899bdd21fa9663cc05741fb15a

This also adds an example good PCRs: https://github.com/osresearch/safeboot/blob/master/tests/pcrs-t490.txt

**Comment by miczyg1** [comment]
That's great, thanks for adding it.
