### ISSUE TITLE
tpm2-attest network demo

### ISSUE THREAD

**Issue by osresearch** [osresearch/safeboot#73]
Need an easy demo to show how to use it across a network.

**Comment by osresearch** [comment]
Google has vTPM: https://cloud.google.com/blog/products/gcp/virtual-trusted-platform-module-for-shielded-vms-security-in-plaintext

Azure does not: https://docs.microsoft.com/en-us/azure/virtual-machines/generation-2#on-premises-vs-azure-generation-2-vms

Not sure about AWS, last forum post was from 2011 about it.

**Comment by osresearch** [comment]
TPM2 shows up in gcp like normal.  `tpm2` tools in this repo work (although #75 and a few other bugs).
```
sudo dmesg | grep -i tpm
[    0.034382] ACPI: SSDT 0x000000003F3F8000 000316 (v02 GOOGLE Tpm2Tabl 00001000 INTL 20160527)
[    0.037190] ACPI: TPM2 0x000000003F3F7000 000034 (v04 GOOGLE          00000001 GOOG 00000001)
[    4.129152] tpm_tis MSFT0101:00: 2.0 TPM (device-id 0x9009, rev-id 0)
```
```
sudo ./bin/tpm2 pcrread sha256:0,1,2,3,4,5,6,7
sha256:
  0 : 0xFCECB56ACC303862B30EB342C4990BEB50B5E0AB89722449C2D9A73F37B019FE
  1 : 0x0000000000000000000000000000000000000000000000000000000000000000
  2 : 0x0000000000000000000000000000000000000000000000000000000000000000
  3 : 0x0000000000000000000000000000000000000000000000000000000000000000
  4 : 0x2606F6F23F7CBAE99FDED25D1DB335DDBACB224529024949554F0CD78FE7D22E
  5 : 0x3D9BC6D61EC1CA87240D623D9AF2C4E2CC1DC5C2AE8AF987B422AE95ECAEC678
  6 : 0x0000000000000000000000000000000000000000000000000000000000000000
  7 : 0x61AF3F499F1A86BE54458FD30D193FA913A7E23CA3103FA3D0ABAEFD3CD4F9B8
```

**Comment by osresearch** [comment]
Secure Boot is not enabled by default, need to  [turn on SecureBoot](https://cloud.google.com/compute/docs/instances/modifying-shielded-vm)
```
sudo dmesg | grep -i secure
[    0.000000] secureboot: Secure boot could not be determined (mode 0)
```

TPM event log is not present:
```
sudo cat /sys/kernel/security/tpm0/binary_bios_measurements > events
cat: /sys/kernel/security/tpm0/binary_bios_measurements: No such file or directory
```

TPM does not have an NV certificate at the expected location:
```
tpm2 nvread -o /tmp/tmp.Lt2WTiraXL/ek.crt 0x01c00002
WARNING:esys:src/tss2-esys/api/Esys_NV_ReadPublic.c:309:Esys_NV_ReadPublic_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/esys_tr.c:210:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000018b) 
ERROR:esys:src/tss2-esys/esys_tr.c:321:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b) 
ERROR: Esys_TR_FromTPMPublic(0x18B) - tpm:handle(1):the handle is not correct for the use
ERROR: Invalid handle authorization
ERROR: Unable to run nvread
```

**Comment by osresearch** [comment]
After enabling secureboot, the eventlog is now present, but unparsable. https://github.com/tpm2-software/tpm2-tools/issues/2204

**Comment by osresearch** [comment]
After hacking up `tpm2-attest` to ignore the missing cert and eventlog, the rest of the quote / validate / seal / unseal process works (although it is completely untrustworthy without those two pieces)

**Comment by osresearch** [comment]
Google replied that the vTPM is a software-only and that they do not have EK certs right now.  They are looking into the event log issue.

Details on setting PK/KEK/db and building images to boot from ESP `\EFI\Boot\bootx64.efi` https://cloud.google.com/security/shielded-cloud/creating-shielded-images

**Comment by josephlr** [comment]
@osresearch I'm Joe Richey, and I work on vTPM attestation on GCE.

Looking into this eventlog issue:
  - I created a new GCE Ubuntu 20.04 instance (which enables vTPM by default)
  - I built safeboot (`sudo make requirements && make`)
  - I ran the following commands:
    ```bash
    sudo cp /sys/kernel/security/tpm0/binary_bios_measurements eventlog.bin
    ./src/safeboot/bin/tpm2 eventlog eventlog.bin > parsed_eventlog.txt
    ```
  - The log seems to parse correctly and produces the events we would expect
    - This includes the `EV_NO_ACTION` containing `Spec ID Event03`
  - The binary and parsed event logs are attached
    - [parsed_eventlog.txt](https://github.com/osresearch/safeboot/files/5285864/parsed_eventlog.txt)
    - [eventlog.bin](https://github.com/osresearch/safeboot/files/5285867/eventlog.bin.txt)


Given that this works on 20.04, this might be a bug in a older version of Linux/Grub.

**Comment by osresearch** [comment]
I had forgotten to include the details about the GCE system, sorry. The invalid test one came from a e2-micro Debian 10 ( debian-10-buster-v20200910) with SecureBoot enabled, which creates the invalid event log. I'll retry with one of the ones that you tested.

**Comment by josephlr** [comment]
> I had forgotten to include the details about the GCE system, sorry. The invalid test one came from a e2-micro Debian 10 ( debian-10-buster-v20200910) with SecureBoot enabled, which creates the invalid event log. I'll retry with one of the ones that you tested.

I was able to reproduce this. Given that it working or not seems to depend on the Image, this is either a bootloader or kernel issue. I'm trying to figure out which one.

**Comment by josephlr** [comment]
I've figured out the issue and (unfortunately) this is an issue with the Linux Kernel and not GCE, so you'll have this problem on most older kernels.

Getting the Event Log to the Kernel involves use of the [TCG EFI Protocol](https://trustedcomputinggroup.org/resource/tcg-efi-protocol-specification/), specifically the `EFI_TCG2_PROTOCOL.GetEventLog` method. This method hands over the log maintained by the firmware to the OS. [Here's where Linux gets the log](https://github.com/torvalds/linux/blob/7c7ec3226f5f33f9c050d85ec20f18419c622ad6/drivers/firmware/efi/libstub/tpm.c#L50-L83).

TCG Event logs have two formats:
  - The legacy SHA1 format (`EFI_TCG2_EVENT_LOG_FORMAT_TCG_1_2`)
  - The new crypto agile format (`EFI_TCG2_EVENT_LOG_FORMAT_TCG_2`)

Despite their names, both can be used with TPM 2.0, so the `GetEventLog` has an `EventLogFormat` parameter. This parameter is used by the OS to request which type of event log it wants.

Linux _used_ to just ask for the old format when TPM2 event log support was first added (https://github.com/torvalds/linux/commit/33b6d03469b2206fb51ecc37f40411a857ad8fff) in 4.16. The kernel was later updated (https://github.com/torvalds/linux/commit/6b0326190205603fa9b7fe1b05ff1f8fb22de266) in 5.3 to:
 - try to get the new format if possible
 - support the variable-length log entreis
 - fall back to the old format if things didn't work

So the logs you're seeing with Debian 10 (kernel 4.19) and RHEL 8 (kernel 4.18) are not malformed, it's just the old format. You should still be able to parse and verify the log, you just have to use SHA1 PCRs to do so (which is obviously very bad, as the TPM's security model can rely on the collision resistance of the PCR's hash algorithm).

**Comment by osresearch** [comment]
Signing the vTPM EK and installing the cert into the nvram at the expected index works #85. This allows quotes to be generated.
